### ISSUE TITLE
QUIC

### ISSUE THREAD

**Issue by moyunmo** [sunlongbo/SimpleQuic#1]
你好，我最近也在研究QUIC，chromium太大，翻墙down 总是失败，你是怎么下载下来的啊。
 还有精简的主要是哪一块？

**Comment by sunlongbo** [comment]
一直拉取失败的话可以直接从github上下载 git clone https://github.com/chromium/chromium.git
但是需要一些配置，具体可以参照我之前写的文章：
https://www.jianshu.com/p/aed96e11fe36

**Comment by sunlongbo** [comment]
> 你好，我最近也在研究QUIC，chromium太大，翻墙down 总是失败，你是怎么下载下来的啊。
> 还有精简的主要是哪一块？

一直拉取失败的话可以直接从github上下载 git clone https://github.com/chromium/chromium.git
但是需要一些配置，具体可以参照我之前写的文章：
https://www.jianshu.com/p/aed96e11fe36

精简的内容比较多主要思想是删除不需要的http1, http2/spdy,及老版本的QUIC协议，简化dns解析，无需支持代理及隐私模式等浏览器才需要支持的逻辑等等 我有时间会持续更新 https://www.jianshu.com/p/6a199103cefd
